plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.myapp'
    compileSdk 36

    defaultConfig {
        applicationId "com.example.myapp"
        minSdk 21
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file('../myapp.keystore')
            storePassword 't3sdk2026'
            keyAlias 'myapp'
            keyPassword 't3sdk2026'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
